meta_title: "Greenthumbs"
meta_description: "Start growing your veggies next door. Find your urban garden at Greenthumbs."
meta_image: "garden1.jpeg" # Une image dans votre dossier app/assets/images/
twitter_account: "@JojannekeTamis" # indispensable pour les Twitter Cards

